In [1]:
import pandas as pd
import re
pd.set_option('display.max_colwidth',200)

In [7]:
df = pd.read_fwf('Chat.txt')
df

7/12/18 19:54 - Los mensajes y llamadas en este chat ahora están protegidos con cifrado de extremo a extremo. Toca  \
0                                                                                            7/12/18 19:54 - 785495: Hi   
1                                                                           7/12/18 19:55 - 785495: Oye una duda rápida   
2                                                  7/12/18 19:55 - 785495: Recuerdas q pregunta Nieto en la exposiciòn?   
3                                                                                           7/12/18 21:16 - Ricardo: Hi   
4                                                                              7/12/18 21:18 - Ricardo: Nada específico   
5                    7/12/18 21:18 - Ricardo: Solo si no es el modelo correcto té cuestióna y te dice cuál era el mejor   
6                                                  7/12/18 21:19 - Ricardo: Y hace preguntas vagas sobre tu caso de uso   
7                                                                               7/12/18 21:19 - 785495: Cuqnto sacqron?   
8                                                                                   7/12/18 21:19 - 785495: Te acuerdas   
9                                                                                    7/12/18 21:20 - Ricardo: Nosotros?   
10                                                                                           7/12/18 21:20 - 785495: Si   
11                                                                               7/12/18 21:20 - Ricardo: 10 en la Expo   
12                                                                                 7/12/18 21:20 - Ricardo: 10 proyecto   
13                                                                                           7/12/18 21:21 - 785495: Va   
14                                                                                 7/12/18 21:21 - Ricardo: 6 en examen   
15                                                                                    7/12/18 21:21 - Ricardo: O 7 creo   
16                                                                                  7/12/18 21:21 - Ricardo: Final yo 8   
17                                                                               7/12/18 21:21 - Ricardo: Daniel 9 o 10   
18                                                                                7/12/18 21:21 - Ricardo: Y Federico 8   
19                                                                     7/12/18 21:21 - Ricardo: A mí me trono el examen   
20                                                            7/12/18 21:22 - Ricardo: Tareas y Expo y proyecto todo 10   
21   7/12/18 21:23 - Ricardo: Necesitaba 10 en la Expo y proyecto para pasar con 8 y no me cobraran la materia en Atlas   
22                                                                     7/12/18 21:23 - Ricardo: No hay otra explicación   
23                                                                                           7/12/18 21:24 - 785495: Ok   
24                                                                      7/12/18 21:24 - Ricardo: Bueno si, un milagro 😇   
25                                                                           7/12/18 21:24 - Ricardo: Mejor ya descansa   
26                                                  7/12/18 21:24 - 785495: Solo pa saber  mas menos andamos guiandonos   
27                                                                              7/12/18 21:24 - 785495: Para el reporte   
28                                           7/12/18 21:24 - Ricardo: Y vete a jugar con tu hijo...eso sí es importante   
29                                                                               7/12/18 21:25 - 785495: Es es el lunes   
..                                                                                                                  ...   
236                                                                  

In [14]:
df['chat']=df.iloc[:,0].apply(lambda x: str(x).split("-")[1])
#df.iloc[:,0]
df

7/12/18 19:54 - Los mensajes y llamadas en este chat ahora están protegidos con cifrado de extremo a extremo. Toca  \
0                                                                                            7/12/18 19:54 - 785495: Hi   
1                                                                           7/12/18 19:55 - 785495: Oye una duda rápida   
2                                                  7/12/18 19:55 - 785495: Recuerdas q pregunta Nieto en la exposiciòn?   
3                                                                                           7/12/18 21:16 - Ricardo: Hi   
4                                                                              7/12/18 21:18 - Ricardo: Nada específico   
5                    7/12/18 21:18 - Ricardo: Solo si no es el modelo correcto té cuestióna y te dice cuál era el mejor   
6                                                  7/12/18 21:19 - Ricardo: Y hace preguntas vagas sobre tu caso de uso   
7                                                                               7/12/18 21:19 - 785495: Cuqnto sacqron?   
8                                                                                   7/12/18 21:19 - 785495: Te acuerdas   
9                                                                                    7/12/18 21:20 - Ricardo: Nosotros?   
10                                                                                           7/12/18 21:20 - 785495: Si   
11                                                                               7/12/18 21:20 - Ricardo: 10 en la Expo   
12                                                                                 7/12/18 21:20 - Ricardo: 10 proyecto   
13                                                                                           7/12/18 21:21 - 785495: Va   
14                                                                                 7/12/18 21:21 - Ricardo: 6 en examen   
15                                                                                    7/12/18 21:21 - Ricardo: O 7 creo   
16                                                                                  7/12/18 21:21 - Ricardo: Final yo 8   
17                                                                               7/12/18 21:21 - Ricardo: Daniel 9 o 10   
18                                                                                7/12/18 21:21 - Ricardo: Y Federico 8   
19                                                                     7/12/18 21:21 - Ricardo: A mí me trono el examen   
20                                                            7/12/18 21:22 - Ricardo: Tareas y Expo y proyecto todo 10   
21   7/12/18 21:23 - Ricardo: Necesitaba 10 en la Expo y proyecto para pasar con 8 y no me cobraran la materia en Atlas   
22                                                                     7/12/18 21:23 - Ricardo: No hay otra explicación   
23                                                                                           7/12/18 21:24 - 785495: Ok   
24                                                                      7/12/18 21:24 - Ricardo: Bueno si, un milagro 😇   
25                                                                           7/12/18 21:24 - Ricardo: Mejor ya descansa   
26                                                  7/12/18 21:24 - 785495: Solo pa saber  mas menos andamos guiandonos   
27                                                                              7/12/18 21:24 - 785495: Para el reporte   
28                                           7/12/18 21:24 - Ricardo: Y vete a jugar con tu hijo...eso sí es importante   
29                                                                               7/12/18 21:25 - 785495: Es es el lunes   
..                                                                                                                  ...   
236                                                                  

In [15]:
convo = df.iloc[:,4]
convo

0                                                                                               785495: Hi
1                                                                              785495: Oye una duda rápida
2                                                     785495: Recuerdas q pregunta Nieto en la exposiciòn?
3                                                                                              Ricardo: Hi
4                                                                                 Ricardo: Nada específico
5                       Ricardo: Solo si no es el modelo correcto té cuestióna y te dice cuál era el mejor
6                                                     Ricardo: Y hace preguntas vagas sobre tu caso de uso
7                                                                                  785495: Cuqnto sacqron?
8                                                                                      785495: Te acuerdas
9                                    

In [53]:
clist = []
for i in range(len(df)-1):
    x=convo[i]
    y=convo[i+1]
#print(x,y)
    cpairs=re.findall(r": (.*?)(?:$|\\n)", x)
    cpairs1=re.findall(r": (.*?)(?:$|\\n)", y)
#print(cpairs,cpairs1)
    clist.extend(list(zip(cpairs, cpairs1)))
#clist

In [55]:
#convo.map(qa_pairs)
clist

[('Hi', 'Oye una duda rápida'),
 ('Oye una duda rápida', 'Recuerdas q pregunta Nieto en la exposiciòn?'),
 ('Recuerdas q pregunta Nieto en la exposiciòn?', 'Hi'),
 ('Hi', 'Nada específico'),
 ('Nada específico',
  'Solo si no es el modelo correcto té cuestióna y te dice cuál era el mejor'),
 ('Solo si no es el modelo correcto té cuestióna y te dice cuál era el mejor',
  'Y hace preguntas vagas sobre tu caso de uso'),
 ('Y hace preguntas vagas sobre tu caso de uso', 'Cuqnto sacqron?'),
 ('Cuqnto sacqron?', 'Te acuerdas'),
 ('Te acuerdas', 'Nosotros?'),
 ('Nosotros?', 'Si'),
 ('Si', '10 en la Expo'),
 ('10 en la Expo', '10 proyecto'),
 ('10 proyecto', 'Va'),
 ('Va', '6 en examen'),
 ('6 en examen', 'O 7 creo'),
 ('O 7 creo', 'Final yo 8'),
 ('Final yo 8', 'Daniel 9 o 10'),
 ('Daniel 9 o 10', 'Y Federico 8'),
 ('Y Federico 8', 'A mí me trono el examen'),
 ('A mí me trono el examen', 'Tareas y Expo y proyecto todo 10'),
 ('Tareas y Expo y proyecto todo 10',
  'Necesitaba 10 en la Expo y pr

In [56]:
convo_frame = pd.Series(dict(clist)).to_frame().reset_index()
convo_frame.columns = ['q', 'a']

In [57]:
convo_frame

q  \
0                                                                                 10 en la Expo   
1                                                                                   10 proyecto   
2                                                                                   6 en examen   
3                                                                          <Multimedia omitido>   
4                                                                                           ???   
5                                                                               A darle átomos!   
6                                                                           A huevo tu muy bien   
7                                                                       A mí me trono el examen   
8                                                    A ver si la próxima semana nos podemos ver   
9                                                                                       Aguas!!   
10                                                                              Ah no velda?! 😅   
11                                               Ahí en Rio Lerma hay varios lugares agradables   
12                                                                                          Aja   
13                           Aja ya ves q puedes sacar los datos de todas tus apps de google...   
14                                                                           Algún cliente loco   
15                                                         Andale las apis pa sacar tus correos   
16   Ando en friega, justo estoy viendo eso ya me ofertaron allá y ahora voy a ver una oferta d   
17                                                                            Aquí la evidencia   
18                                                                                       Asi ew   
19                                                                                       Así es   
20                                                        Aun no pero mi exjefa me contraoferto   
21                                      Banco+ retail+ tv  imaginate saber todo eso de la gente   
22                                                                              Bancomer en eso   
23                                                                      Bancomer es más empresa   
24                                                                             Base son 45netos   
25                                                  Bnmr Vs Salinas en prestaciones quién gana?   
26                                                                       Bueno si, un milagro 😇   
27                                                                               Buenos días! ☀   
28                                                                                        Claro   
29                                                                             Comenta comenta!   
..                                                                                          ...   
211                                                                    Y ya no me conviene irne   
212                                                                        Ya andas en Salinas?   
213                                                                          Ya ando como en 60   
214                                         Ya con calma organizamos la otra comidita pendiente   
215                                                       Ya eres todo un activo Salinas o que?   
216                                                                  Ya estás con un pie afuera   
217                                                                      Ya lo quiero es qcabar   
218                                            Ya no lp vale por perder antiguedad y vacaciones   
219                                                                             Ya pasó lo peor   
220                                

In [58]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
vectorizer = TfidfVectorizer(ngram_range=(1,3))
vec = vectorizer.fit_transform(convo_frame['q'])

In [67]:
my_q = vectorizer.transform(['casi les dicen que evacuen a las 5pm!!!!'])
cs = cosine_similarity(my_q, vec)
rs = pd.Series(cs[0]).sort_values(ascending=False)
top5 = rs.iloc[0:5]
top5

240    1.000000
15     0.042486
207    0.040779
40     0.040320
154    0.040292
dtype: float64

In [134]:
pd.Series(cs[0])

0      0.000000
1      0.000000
2      0.000000
3      0.000000
4      0.000000
5      0.000000
6      0.000000
7      0.000000
8      0.000000
9      0.000000
10     0.000000
11     0.000000
12     0.000000
13     0.000000
14     0.000000
15     0.042486
16     0.000000
17     0.000000
18     0.000000
19     0.000000
20     0.000000
21     0.000000
22     0.000000
23     0.000000
24     0.000000
25     0.000000
26     0.000000
27     0.000000
28     0.000000
29     0.000000
         ...   
211    0.000000
212    0.000000
213    0.000000
214    0.000000
215    0.022669
216    0.000000
217    0.000000
218    0.000000
219    0.000000
220    0.000000
221    0.000000
222    0.015108
223    0.000000
224    0.000000
225    0.000000
226    0.000000
227    0.000000
228    0.000000
229    0.000000
230    0.000000
231    0.000000
232    0.000000
233    0.000000
234    0.000000
235    0.000000
236    0.000000
237    0.000000
238    0.000000
239    0.000000
240    1.000000
Length: 241, dtype: floa

In [68]:
convo_frame.iloc[top5.index]['q']

240                                                    🤣 casi les dicen que evacuen a las 5pm!!!!
15                                                           Andale las apis pa sacar tus correos
207                                                                                Y nada que ver
40     Consulte con un compa de la maestría de las primeras generaciones y me dijo que si era mat
154           Si claro, conozco gente que paso por ahí en buenos niveles de TI, y no les fue bien
Name: q, dtype: object

In [70]:
rsi = rs.index[0]
rsi
convo_frame.iloc[rsi]['a']

'Si no manches eso que'

In [71]:
def get_response(q):
    my_q = vectorizer.transform([q])
    cs = cosine_similarity(my_q, vec)
    rs = pd.Series(cs[0]).sort_values(ascending=False)
    rsi = rs.index[0]
    return convo_frame.iloc[rsi]['a']

In [84]:
get_response('we, pero ya ')

'Ya ando como en 60'

In [82]:
vec.shape

(241, 2114)

In [88]:
my_q[0,213]

0.0

In [95]:
import numpy as np
np.where(my_q0)

/home/mb45296/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2881: SparseEfficiencyWarning: Comparing a sparse matrix with 0 using == is inefficient, try using != instead.
  exec(code_obj, self.user_global_ns, self.user_ns)


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all().

In [91]:
np.array(my_q)

array(<1x2114 sparse matrix of type '<class 'numpy.float64'>'
	with 18 stored elements in Compressed Sparse Row format>, dtype=object)

In [99]:
import re

def generate_ngrams(s, n):
    # Convert to lowercases
    s = s.lower()
    
    # Replace all none alphanumeric characters with spaces
    s = re.sub(r'[^a-zA-Z0-9\s]', ' ', s)
    
    # Break sentence in the token, remove empty tokens
    tokens = [token for token in s.split(" ") if token != ""]
    
    # Use the zip function to help us generate n-grams
    # Concatentate the tokens into ngrams and return
    ngrams = zip(*[token[i:] for i in range(n)])
    return [" ".join(ngram) for ngram in ngrams]

In [100]:
generate_ngrams(my_q, 3)

AttributeError: lower not found

In [103]:
vectorizer.get_feature_names()

['10',
 '10 en',
 '10 en la',
 '10 mas',
 '10 proyecto',
 '100',
 '100 de',
 '100 de la',
 '30',
 '30 hrs',
 '30 hrs para',
 '30 mas',
 '30 mas anual',
 '45netos',
 '5pm',
 '60',
 'aabe',
 'acaba',
 'acaba de',
 'acaba de entrar',
 'acaban',
 'acaban de',
 'acaban de llevar',
 'acep',
 'acercarse',
 'acercarse les',
 'acercarse les dejan',
 'activo',
 'activo salinas',
 'activo salinas que',
 'acuerdas',
 'acá',
 'acá no',
 'acá no podemos',
 'además',
 'además de',
 'además de la',
 'afuera',
 'agradables',
 'aguas',
 'ah',
 'ah no',
 'ah no velda',
 'ahora',
 'ahora es',
 'ahora es como',
 'ahora sí',
 'ahora sí buscarle',
 'ahora va',
 'ahora va ser',
 'ahora voy',
 'ahora voy ver',
 'ahí',
 'ahí en',
 'ahí en buenos',
 'ahí en rio',
 'ahí esta',
 'ahí esta la',
 'aja',
 'aja ya',
 'aja ya ves',
 'al',
 'al final',
 'al final no',
 'al ginal',
 'al ginal de',
 'al rato',
 'al rato en',
 'alertas',
 'alertas de',
 'alertas de bombiux',
 'algo',
 'algo con',
 'algo con tu',
 'algún',


In [120]:
#cosine_similarity(my_q, vec)
np.where(vec[240,:].toarray()>0)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([  14,  217,  218,  219,  483,  484,  485,  735,  736,  737, 1003,
        1004, 1024, 1026, 1027, 1531, 1534, 1535]))

In [125]:
a=my_q.toarray()[np.where(my_q.toarray()>0)]
a

array([0.24411405, 0.24411405, 0.24411405, 0.24411405, 0.24411405,
       0.24411405, 0.24411405, 0.24411405, 0.24411405, 0.24411405,
       0.20552062, 0.24411405, 0.20552062, 0.24411405, 0.24411405,
       0.14713101, 0.24411405, 0.24411405])

In [126]:
b=vec[240,:].toarray()[np.where(vec[240,:].toarray()>0)]
b

array([0.24411405, 0.24411405, 0.24411405, 0.24411405, 0.24411405,
       0.24411405, 0.24411405, 0.24411405, 0.24411405, 0.24411405,
       0.20552062, 0.24411405, 0.20552062, 0.24411405, 0.24411405,
       0.14713101, 0.24411405, 0.24411405])

In [144]:
cosine_similarity(a.reshape(1,18),b.reshape(1,18))

array([[1.]])

In [143]:
a.shape

(18,)

In [155]:
from __future__ import print_function
from nltk.chat.util import Chat, reflections

In [163]:
def chateo():
    msg=""
    while(msg!="bye"):
        msg=input()
        if msg=="bye":
            print("bye")
            break
        else:
            print(get_response(msg))
        
    #print("bye")    


In [165]:
chateo()

hola
Como estamos?
bien y tu?
😬
que te pasa?
Ewo sí
como?
Aja ya ves q puedes sacar los datos de todas tus apps de google...
neta?
Si no manches eso que
jajaja
Nomas spamean a la banda 😆
bye
bye
